patches/luvos.patch

patches: update the luvos.patch for sbsa-acs changes

---

patches/luvos.patch

sbbr/sbsa option now comes in grub menu
increase initramfs max size

patches: bug fixes

---

README.md
patches/luvos.patch

Append kernel command line parameters at build time
Provide dtb file for non-ACPI systems

patches: customize build parameters

---

README.md
patches/luvos.patch

Signed-off-by: Prasanth Pulla <Prasanth.Pulla@arm.com>

misc: documentation updated and build bug fix

---

patches/luvos.patch

patches: add startup script to run sbsa and boot luvOS

---

patches/luvos.patch

SBSA: Update checkout branch/tag for sbsa-acs and linux-acs

---

patches/luvos.patch

Signed-off-by: Vishwanatha HG <Vishwanatha.HG@arm.com>

Enhancements in build and logging scripts

---

README.md

Final edits to be reviewed before checking the content in.

Updated README for final changes.

---

patches/luvos.patch

Minor build changes

---

patches/luvos.patch

Update fwts luv-test scripts better logs

---

patches/luvos.patch

Build SBSA efi app on UDK2017 edk2 branch

---

patches/luvos.patch

Build bug fix for release branch

---

acs_sync.sh
check_deps.sh
patches/luvos.patch

Update license information in multiple files

---

patches/luvos.patch

Signed-off-by: Vishwanatha HG <vishwanatha.hg@arm.com>

Checkout v.17.07_REL1.0 tag of sbsa-acs repo

---

patches/luvos.patch

Checkout the fwts commit with all the latest
sbbr changes.

patches/fwts: update fwts checkout commit-id

---

README.md

Signed-off-by: Andy Gospodarek <gospo@broadcom.com>

README: Fix broken link to SCT User Guide

---

sbbr/scripts/sbbr.bb
sbsa/scripts/sbsa-acs-test.bb
sbsa/scripts/sbsa-acs-val.bb
sbsa/scripts/sbsa.bb
sdei/linux_app/sdei-acs-app/sdei-acs-app.bb
sdei/scripts/sdei-acs-test_0.1.bb
sdei/scripts/sdei-acs-val_0.1.bb
sdei/scripts/sdei.bb

Signed-off-by: Mahesh Bireddy <mahesh.reddybireddy@arm.com>

Adds license header to all bb files

---

patches/luvos.patch
prebuilt_images/v18.12_REL1.7/luv-live-image-gpt.img

v18.12_REL1.7: Added prebuilt image. Updated release tags

---

patches/luvos.patch
prebuilt_images/v18.12_REL1.7/luv-live-image-gpt.img

Also, update tag info in sbsa bitbake script.

v18.12_REL1.7: Update prebuilt image

---

prebuilt_images/v18.12_REL1.7/luv-live-image-gpt.img

v18.12_REL1.7: Added pre-built image

---

acs_sync.sh
luvos/scripts/build.sh
luvos/scripts/setup.sh
sbbr/scripts/sbbr.bb

Release Version 2.2

---

README.md
sbbr/README.md

Updated Release Versions in README

Changes for Release Version 2.3

---

luvos/patches/luvos.patch
sbsa/patches/ShellSbsa.patch
sbsa/scripts/buildshellsbsa.sh
sbsa/scripts/compile.sh
sbsa/scripts/sbsa-acs-val.bb
sbsa/scripts/sbsa.bb

- Modified scripts to use the latest EDKII branch tagged
edk2-stable202008
Signed-off-by: Gowtham Siddarth <gowtham.siddarth@arm.com>

EDKII: Migration to edk2-stable202008 for SBSA ACS v3.0

---

README.md
mpam/README.md
sdei/scripts/sdei.bb

Updated link for Pre-Built images and sbsa commit-id in README.
Minor Improvements
Signed-off-by: G Edhaya Chandran <edhaya.chandran@arm.com>

Updates in README

---

luvos/patches/0001-8250_fsl.patch
luvos/patches/0001-SPCR-Consider-baud-rate-0-as-preconfigured-state.patch
luvos/patches/luvos.patch
luvos/scripts/setup.sh

Signed-off-by: Sujana M <sujana.m@arm.com>

SPCR: Added patch for SPCR

---

luvos/patches/0001-8250_tegra-Create-Tegra-specific-8250-driver.patch
luvos/patches/luvos.patch
luvos/scripts/setup.sh

Signed-off-by: Sujana M <sujana.m@arm.com>

Added Tegra patch

---

mpam/scripts/acsbuild.sh

Signed-off-by: Adrian Herrera <adrian.herrera@arm.com>

fix(mpam): path to MpamAcs.inf from acsbuild.sh

---

README.md
luvos/patches/luvos.patch

Updated luvos.patch to remove  unwanted tests during LuvOS startup
Solution for : https://github.com/ARM-software/arm-enterprise-acs/issues/92
Updated README with a note for SCT for the issue: https://github.com/ARM-software/arm-enterprise-acs/issues/106

Updated luvos.patch and README.md

---

sbbr/patches/sbbr-fwts.patch

The patch: 
https://kernel.ubuntu.com/git/hwe/fwts.git/patch/?id=2ff5a219f2eb818f11ff48ef2c041b149ea76c63
is included as a solution for the issue : 
https://github.com/ARM-software/arm-enterprise-acs/issues/103

Included the SPCR baurate patch for FWTS
